// <auto-generated />
using System;
using DogWalkingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogWalkingApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127173445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogWalkingApi.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Labrador",
                            Name = "Buddy",
                            OwnerId = 1,
                            Size = "Large"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            Breed = "Beagle",
                            Name = "Max",
                            OwnerId = 2,
                            Size = "Medium",
                            SpecialNeeds = "Allergic to chicken"
                        });
                });

            modelBuilder.Entity("DogWalkingApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "hashedpassword1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob",
                            PasswordHash = "hashedpassword2"
                        });
                });

            modelBuilder.Entity("DogWalkingApi.Models.Walk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WalkDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DogId = 1,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Status = "Scheduled",
                            WalkDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            WalkerId = 2
                        },
                        new
                        {
                            Id = 2,
                            DogId = 2,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Status = "Scheduled",
                            WalkDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            WalkerId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
